import '../public/css/bootstrap.min.css'
import '../public/css/animate.min.css'
import '../public/css/magnific-popup.css'
import '../public/css/fontawesome-all.min.css'
import '../public/css/imageRevealHover.css'
import '../public/css/swiper-bundle.css'
import '../public/css/flaticon.css'
import '../public/css/slick.css'
import '../public/css/spacing.css'
import '../public/css/main.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
	let categories = await fetch('http://localhost:3000/api/categories',{ cache:'no-store'});
	categories     = await categories.json();
	return (
		<html lang="en" tg-theme="light">
			<body>
				<Header categories={categories}></Header>
				{children}
				<Footer categories={categories}></Footer>
			</body>
		</html>
	)
}
