import '../public/css/bootstrap.min.css'
import '../public/css/animate.min.css'
import '../public/css/magnific-popup.css'
import '../public/css/fontawesome-all.min.css'
import '../public/css/imageRevealHover.css'
import '../public/css/swiper-bundle.css'
import '../public/css/flaticon.css'
import '../public/css/slick.css'
import '../public/css/spacing.css'
import '../public/css/main.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
	let categories = [
		{
			"id":1,
			"name" : "Automobiles",
			"slug" : "automobiles"
		},
		{
			"id":2,
			"name" : "Entertainment",
			"slug" : "entertainment"
		},
		{
			"id":3,
			"name" : "Food",
			"slug" : "food"
		},
		{
			"id":4,
			"name" : "Games",
			"slug" : "games"
		},
		{
			"id":5,
			"name" : "Sports",
			"slug" : "sports"
		},
		{
			"id":6,
			"name" : "Travel",
			"slug" : "travel"
		}

	]

	return (
		<html lang="en" tg-theme="light">
			<body>
				<Header categories={categories}></Header>
				{children}
				<Footer categories={categories}></Footer>
			</body>
		</html>
	)
}
